### ISSUE TITLE
Property of non-object.

### ISSUE THREAD

**Issue by jmbarne3** [UCF/UCF-Page-Assets-Plugin#11] opened 2019-08-21 14:51 UTC
Notice: Trying to get property 'ID' of non-object in
[...]plugins/UCF-Page-Assets-Plugin/includes/page-assets-common.php on line 16.

When the global `$post` is not set (as it will not be on taxonomy term pages) this throws a warning.

**Comment by cjg89** [comment] 2019-08-21 14:52
This is a duplicate of #10.

**Closed as completed** 2019-08-21 14:53 UTC
Labels: duplicate
